### ISSUE TITLE
Feat: Create an 'Open Source Programs' Page

### ISSUE THREAD

**Issue by Surajit0573** [Sriparno08/Openpedia#130]
## Category

- [ ] Documentation
- [X] Resource Addition

## Description

I want to add different kind of Open-Source Programs timeline and details on one visually appealing, easily accessible page.
 - Resource  : https://github.com/tapaswenipathak/Open-Source-Programs & Google

**Comment by Surajit0573** [comment]
Please assign me under JWOC after 15th January, if approved.

**Comment by Sriparno08** [comment]
Hey @Surajit0573, since mentees can't raise issues before 15th Jan, I'm closing this one.

However, the project needs an 'Open Source Programs' page and we can go with the structure that you're suggesting. So, I'll open this issue myself and then assign it to you once the first coding period starts.
