### ISSUE TITLE
Chore: Edit and update footer section

### ISSUE THREAD

**Issue by madhurima316** [Sriparno08/Openpedia#182]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description
All the 5 categories under 'Categories' in footer section would be added and would be made interactive so they can redirect to the 'Categories' section and would add the hover effects.

**Comment by madhurima316** [comment]
Please assign me this issue under JWOC 2024.

**Comment by Sriparno08** [comment]
Hey @madhurima316, good ideas. Among these, we can add the 5 categories under 'Categories' in footer section. Since each category will have their own page soon, let's not add links to them now as we will do it once all the pages are made. Plus, let's not apply hover effect yet to the links under 'Categories' as we will do it in the coming stages for all the links in the footer section.

I'm assigning this to you.
