### ISSUE TITLE
Alignment Issue with Dark and Light Mode Toggle in Responsive View (Below 800px)

### ISSUE THREAD

**Issue by mathanraj0601** [Sriparno08/Openpedia#250]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [ ] Codebase
- [x] User Interface
- [ ] Feature Request

## Description
I noticed that the Dark and Light mode toggle is not aligned with the other navigation items when the screen width is below 800px. This alignment issue affects the visual consistency of the user interface.

## Steps to Reproduce
1.Open the application on a device with a screen width below 800px.
2. Navigate to the navigation bar.
3. Observe the alignment of the Dark and Light mode toggle.

![image](https://github.com/Sriparno08/Openpedia/assets/98396468/a7db32ae-1998-4b77-9cb2-1dbff2d34873)

### Interested to contribute in this issue
- [x] Ready to Contribute

**Comment by Sriparno08** [comment]
@mathanraj0601 Nice catch. The thing is, we don't want to have the toggle button as an entry to the navbar that we can see below 800px. Instead, we want it to be located at the left side of the hamburger icon.

This repository is currently participating in JGEC Winter of Code (JWOC) and we have decided that during this period, all the open issues will only be assigned to JWOC participants. If you have registered for this event, then please mention that in your comment. If not, please mention that as well because in that case, this issue will not be assigned to you unfortunately.

**Comment by mathanraj0601** [comment]
Thank you, @Sriparno08!  I'm not currently participating in JWOC, but no worries—I'm looking forward to contributing in the future after the event. For anyone in JWOC who is interested in tackling this issue, go ahead and work on it 🚀. Happy open source, happy coding! ✨

**Comment by Sriparno08** [comment]
Thank you for informing, @mathanraj0601 and great to hear that you are interested in contributing to this project in the future 👍

**Comment by AntonyJudeShaman** [comment]
Hi can i work on this issue? from JWoC

**Comment by antilneeraj** [comment]
@Sriparno08 Please assign this issue to me under JWOC.

**Comment by Sriparno08** [comment]
@antilneeraj You're assigned.

@AntonyJudeShaman The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

**Comment by Sriparno08** [comment]
@antilneeraj You can make it like this:

<p align="center">
  <img src="https://github.com/Sriparno08/Openpedia/assets/89148144/669cdf74-ceb3-4a8e-985e-999cd277566f">
<p>

Don't change the button as another mentee is already working on it.

**Comment by antilneeraj** [comment]
@Sriparno08 I understood that I only need to align the toggle and should not perform any changes in the appearance of the toggle button right?

**Comment by Sriparno08** [comment]
Yeah, correct 👍

**Comment by AntonyJudeShaman** [comment]
> @antilneeraj You're assigned.
> 
> @AntonyJudeShaman The mentee who is assigned to this issue is chosen because he/she was the first one to ask for assignment with the 'JWOC' (Case-Sensitive) keyword in his/her comment.

Oh then the JWoC in my comment means a JCB bulldozer? Can u please visit the JWoC website and see how they have mentioned it?

**Comment by Sriparno08** [comment]
@AntonyJudeShaman As we saw on Discord, there is a comment that says this:

> Comment with **I would like to work on that issue under JWOC** (mentioning JWOC in a comment is compulsory)

Above, both the JWOC keywords are capitalized. Plus, we are advised to use the case-sensitive 'JWOC' label on our issues. That's why, we have decided to look for the case-sensitive 'JWOC' keyword in the issue comments to keep mentees on the safe side because otherwise, the assignee's PR may not get counted for an issue even though he/she wrote the keyword in their comment.

For this issue, it will be unfair to unassign the current assignee. So, we are keeping the assignment intact.

From the next time, please write the case-sensitive 'JWOC' keyword in your comment to ensure that your hard work is rewarded if you make a PR for an issue and avoid any kind of confusion.

Lastly, apologies for all the inconvenience caused. There's a lot of guidelines that we're all getting used to as time passes.

**Comment by Sriparno08** [comment]
@AntonyJudeShaman Since many PRs are getting merged without the assignee mentioning 'JWOC' as case-sensitive, we have decided to just look for the keyword in the comments.

So, from the next time, there is no need to make 'JWOC' case-sensitive. Just make sure you mention it in your comment.

@antilneeraj You also note the above.

**Comment by antilneeraj** [comment]
Alright 👍
