### ISSUE TITLE
Chore: Fix SVG Link in 'Beginner-Friendly Repos' Page

### ISSUE THREAD

**Issue by Sriparno08** [Sriparno08/Openpedia#394]
## Category

- [ ] Documentation
- [ ] Resource Addition
- [x] Codebase
- [ ] User Interface
- [ ] Feature Request

## Description

We need to fix a broken SVG link in the 'Beginner-Friendly Repos' page.

Step 1: Go to `client/pages/beginner-friendly-repos/index.html`
Step 2: Find the following link under `<head>...</head>`

```
<link rel="icon" href="./assets/short-logo.svg">
```

Step 3: Change it to

```
<link rel="icon" href="../../assets/short-logo.jpg">
```

**Comment by GuilhermeJacobRech** [comment]
Assign this issue to me, please.

**Comment by Sriparno08** [comment]
You're assigned, @GuilhermeJacobRech!

**Comment by GuilhermeJacobRech** [comment]
Hello @Sriparno08. Following the instructions won't fix the issue because ..client/assets/short-logo.svg does not exist. Instead, there is a short-logo.png file (note the difference in the extension). I need to know how to procede, should i create a pull request just using the .png extension in codebase or follow the instructions, keep .svg and open a new issue about converting .png to .svg?

**Comment by Sriparno08** [comment]
Good spot, @GuilhermeJacobRech.

I've modified the instructions. Now, just replace the first code block with the second code block and create a pull request.
